site_name: SLIM's Devito examples
site_author: Mathias Louboutin

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: ""

nav:
- 'Home': index.md
- 'Tutorials':
  - Acoustic modeling: tutorials/01_modelling.md
  - Convergence analysis for the acoustic wave-equation: tutorials/accuracy.md
  - Acoustic RTM: tutorials/02_rtm.md
  - Acoustic FWI: tutorials/03_fwi.md
  - Parallel acoustic FWI with Dask: tutorials/04_dask.md
  - First order acoustic modeling: tutorials/05_staggered_acoustic.md
  - Elastic modeling with constant parameters: tutorials/06_elastic.md
  - Elastic modeling with varying parameters: tutorials/07_elastic_varying_parameters.md
- 'The Leading Edge tutorials':
  - Forward modeling: tutorials/TLE_Forward.md
  - Adjoint Modeling: tutorials/TLE_Adjoint.md
  - FWI and algorithms: tutorials/TLE_fwi.md

theme: readthedocs

copyright: Copyright (c) 2020 SLIM group @ Georgia Institute of Technology.

plugins:
    - search

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML

markdown_extensions:
  - mdx_math
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
